# Crime Data 2019

In [1]:
import pandas as pd
import numpy as np
from datetime import datetime, date

In [2]:
#Import csv
raw2019 = pd.read_csv('/csv/2019-PART_I_AND_II_CRIMES.csv', sep = ',')

FileNotFoundError: [Errno 2] No such file or directory: '/csv/2019-PART_I_AND_II_CRIMES.csv'

In [59]:
#Rows and columns
raw2019.shape

(163438, 19)

In [60]:
#Data Types
raw2019.dtypes

LURN_SAK                    int64
INCIDENT_DATE              object
INCIDENT_REPORTED_DATE     object
CATEGORY                   object
STAT                        int64
STAT_DESC                  object
ADDRESS                    object
STREET                     object
CITY                       object
ZIP                       float64
INCIDENT_ID                object
REPORTING_DISTRICT          int64
SEQ                         int64
GANG_RELATED               object
UNIT_ID                    object
UNIT_NAME                  object
LONGITUDE                 float64
LATITUDE                  float64
PART_CATEGORY               int64
dtype: object

In [61]:
#Convert to datetime
raw2019['INCIDENT_DATE'] = pd.to_datetime(raw2019['INCIDENT_DATE'], format = '%m/%d/%Y %I:%M:%S %p')
raw2019['INCIDENT_REPORTED_DATE'] = pd.to_datetime(raw2019['INCIDENT_REPORTED_DATE'], format = '%m/%d/%Y')

#Sort by Incident_Date, Incident_Reported_Date, ID
raw2019 = raw2019.sort_values(by=['INCIDENT_DATE', 'INCIDENT_REPORTED_DATE', 'INCIDENT_ID'], ascending=[True, True, True])
raw2019.dtypes

LURN_SAK                           int64
INCIDENT_DATE             datetime64[ns]
INCIDENT_REPORTED_DATE    datetime64[ns]
CATEGORY                          object
STAT                               int64
STAT_DESC                         object
ADDRESS                           object
STREET                            object
CITY                              object
ZIP                              float64
INCIDENT_ID                       object
REPORTING_DISTRICT                 int64
SEQ                                int64
GANG_RELATED                      object
UNIT_ID                           object
UNIT_NAME                         object
LONGITUDE                        float64
LATITUDE                         float64
PART_CATEGORY                      int64
dtype: object

In [62]:
#Filter by Q1/Q2 2019
start_date = '2018-12-31 23:59:59'
end_date = '2019-06-30 23:59:59'

mask = (raw2019['INCIDENT_DATE'] > start_date) & (raw2019['INCIDENT_DATE'] <= end_date)
s2019 = raw2019.loc[mask]
s2019.reset_index(drop=True)

,LURN_SAK,INCIDENT_DATE,INCIDENT_REPORTED_DATE,CATEGORY,STAT,STAT_DESC,ADDRESS,STREET,CITY,ZIP,INCIDENT_ID,REPORTING_DISTRICT,SEQ,GANG_RELATED,UNIT_ID,UNIT_NAME,LONGITUDE,LATITUDE,PART_CATEGORY
0,18796349,2019-01-01 00:00:00,2019-01-01,NON-AGGRAVATED ASSAULTS,146,"ASSAULT, NON-AGGRAVATED: DOMESTIC VIOLENCE","44300 CAMELIA ST, LANCASTER, CA",44300 CAMELIA ST,LANCASTER,NaN,019-00020-1137,1137,20,NO,CA0190024,LANCASTER,-118.080,34.688,2
1,18796363,2019-01-01 00:00:00,2019-01-01,VEHICLE / BOATING LAWS,250,"VEHICLE AND BOATING LAWS: Hit And Run, Misdeme...","16000 PIONEER BLVD, NORWALK, CA",16000 PIONEER BLVD,NORWALK,NaN,919-00016-0455,455,16,NO,CA0190004,NORWALK,-118.083,33.885,2
2,18796382,2019-01-01 00:00:00,2019-01-01,LARCENY THEFT,89,"GRAND THEFT: Other (From Boat, Plane, Prvt Res...","HAZARD AVE AND FAIRMOUNT ST, LOS ANGELES, CA",HAZARD AVE AND FAIRMOUNT ST,LOS ANGELES,NaN,919-00019-0272,272,19,NO,CA0190002,EAST LOS ANGELES,-118.179,34.046,1
3,18796434,2019-01-01 00:00:00,2019-01-01,VEHICLE / BOATING LAWS,250,"VEHICLE AND BOATING LAWS: Hit And Run, Misdeme...","14TH ST AND RAILROAD AVE, NEWHALL, CA 91321",14TH ST AND RAILROAD AVE,NEWHALL,91321.0,919-00021-0625,625,21,NO,CA0190006,SANTA CLARITA VALLEY,-118.532,34.385,2
4,18799717,2019-01-01 00:00:00,2019-01-04,LARCENY THEFT,387,"THEFT, PETTY: From Bldgs (Church, School, Rest...","600 N ROBERTSON BLVD, WEST HOLLYWOOD, CA 90069",600 N ROBERTSON BLVD,WEST HOLLYWOOD,90069.0,919-00103-0972,972,103,NO,CA0190009,WEST HOLLYWOOD,-118.385,34.083,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81189,18979069,2019-06-30 23:33:00,2019-06-30,DRUNK / ALCOHOL / DRUGS,201,DRUNK: Alcohol,"30100 AGOURA RD, AGOURA HILLS, CA 91301",30100 AGOURA RD,AGOURA HILLS,91301.0,919-03620-2224,2224,3620,NO,CA0190022,MALIBU/LOST HILLS,-118.779,34.144,2
81190,18981219,2019-06-30 23:40:00,2019-07-03,FRAUD AND NSF CHECKS,161,DEFRAUDING: Defrauding Innkeeper (Fel Or Misd),"9300 ROSECRANS AVE, BELLFLOWER, CA 90706",9300 ROSECRANS AVE,BELLFLOWER,90706.0,919-14369-1332,1332,14369,NO,CA0190013,LAKEWOOD,-118.135,33.904,2
81191,18979450,2019-06-30 23:49:00,2019-07-01,DISORDERLY CONDUCT,217,DISORDERLY CONDUCT: Telephone Annoyance,"16100 WOODRUFF AVE, BELLFLOWER, CA 90706",16100 WOODRUFF AVE,BELLFLOWER,90706.0,919-14201-1333,1333,14201,NO,CA0190013,LAKEWOOD,-118.116,33.888,2
81192,18979091,2019-06-30 23:50:00,2019-07-01,ROBBERY,33,"ROBBERY, WEAPON: Service Station","8300 PEARBLOSSOM HWY, LITTLEROCK, CA 93543",8300 PEARBLOSSOM HWY,LITTLEROCK,93543.0,919-09275-2660,2660,9275,NO,CA01900W9,PALMDALE,-117.980,34.519,1
81193,18979108,2019-06-30 23:54:00,2019-07-01,AGGRAVATED ASSAULT,54,"ASSAULT, AGGRAVATED: ADW - HANDS, FEET, FIST, ...","5000 W AVENUE L-3, LANCASTER, CA",5000 W AVENUE L-3,LANCASTER,NaN,019-13794-1182,1182,13794,NO,CA0190024,LANCASTER,-118.219,34.657,1

In [63]:
#Filter columns
f2019 = s2019[["INCIDENT_DATE", "CATEGORY", "STAT", "STAT_DESC", "ADDRESS", "STREET", "CITY", "ZIP", "INCIDENT_ID", "REPORTING_DISTRICT", "GANG_RELATED", "UNIT_ID", "UNIT_NAME", "LONGITUDE", "LATITUDE", "PART_CATEGORY"]]
f2019.reset_index(drop=True)

,INCIDENT_DATE,CATEGORY,STAT,STAT_DESC,ADDRESS,STREET,CITY,ZIP,INCIDENT_ID,REPORTING_DISTRICT,GANG_RELATED,UNIT_ID,UNIT_NAME,LONGITUDE,LATITUDE,PART_CATEGORY
0,2019-01-01 00:00:00,NON-AGGRAVATED ASSAULTS,146,"ASSAULT, NON-AGGRAVATED: DOMESTIC VIOLENCE","44300 CAMELIA ST, LANCASTER, CA",44300 CAMELIA ST,LANCASTER,NaN,019-00020-1137,1137,NO,CA0190024,LANCASTER,-118.080,34.688,2
1,2019-01-01 00:00:00,VEHICLE / BOATING LAWS,250,"VEHICLE AND BOATING LAWS: Hit And Run, Misdeme...","16000 PIONEER BLVD, NORWALK, CA",16000 PIONEER BLVD,NORWALK,NaN,919-00016-0455,455,NO,CA0190004,NORWALK,-118.083,33.885,2
2,2019-01-01 00:00:00,LARCENY THEFT,89,"GRAND THEFT: Other (From Boat, Plane, Prvt Res...","HAZARD AVE AND FAIRMOUNT ST, LOS ANGELES, CA",HAZARD AVE AND FAIRMOUNT ST,LOS ANGELES,NaN,919-00019-0272,272,NO,CA0190002,EAST LOS ANGELES,-118.179,34.046,1
3,2019-01-01 00:00:00,VEHICLE / BOATING LAWS,250,"VEHICLE AND BOATING LAWS: Hit And Run, Misdeme...","14TH ST AND RAILROAD AVE, NEWHALL, CA 91321",14TH ST AND RAILROAD AVE,NEWHALL,91321.0,919-00021-0625,625,NO,CA0190006,SANTA CLARITA VALLEY,-118.532,34.385,2
4,2019-01-01 00:00:00,LARCENY THEFT,387,"THEFT, PETTY: From Bldgs (Church, School, Rest...","600 N ROBERTSON BLVD, WEST HOLLYWOOD, CA 90069",600 N ROBERTSON BLVD,WEST HOLLYWOOD,90069.0,919-00103-0972,972,NO,CA0190009,WEST HOLLYWOOD,-118.385,34.083,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81189,2019-06-30 23:33:00,DRUNK / ALCOHOL / DRUGS,201,DRUNK: Alcohol,"30100 AGOURA RD, AGOURA HILLS, CA 91301",30100 AGOURA RD,AGOURA HILLS,91301.0,919-03620-2224,2224,NO,CA0190022,MALIBU/LOST HILLS,-118.779,34.144,2
81190,2019-06-30 23:40:00,FRAUD AND NSF CHECKS,161,DEFRAUDING: Defrauding Innkeeper (Fel Or Misd),"9300 ROSECRANS AVE, BELLFLOWER, CA 90706",9300 ROSECRANS AVE,BELLFLOWER,90706.0,919-14369-1332,1332,NO,CA0190013,LAKEWOOD,-118.135,33.904,2
81191,2019-06-30 23:49:00,DISORDERLY CONDUCT,217,DISORDERLY CONDUCT: Telephone Annoyance,"16100 WOODRUFF AVE, BELLFLOWER, CA 90706",16100 WOODRUFF AVE,BELLFLOWER,90706.0,919-14201-1333,1333,NO,CA0190013,LAKEWOOD,-118.116,33.888,2
81192,2019-06-30 23:50:00,ROBBERY,33,"ROBBERY, WEAPON: Service Station","8300 PEARBLOSSOM HWY, LITTLEROCK, CA 93543",8300 PEARBLOSSOM HWY,LITTLEROCK,93543.0,919-09275-2660,2660,NO,CA01900W9,PALMDALE,-117.980,34.519,1
81193,2019-06-30 23:54:00,AGGRAVATED ASSAULT,54,"ASSAULT, AGGRAVATED: ADW - HANDS, FEET, FIST, ...","5000 W AVENUE L-3, LANCASTER, CA",5000 W AVENUE L-3,LANCASTER,NaN,019-13794-1182,1182,NO,CA0190024,LANCASTER,-118.219,34.657,1

In [54]:
#Count null values for each column
f2019.isnull().sum()

INCIDENT_DATE             0
CATEGORY                  0
STAT                      0
STAT_DESC                 0
ADDRESS                 765
STREET                 1113
CITY                    765
ZIP                   37193
INCIDENT_ID               0
REPORTING_DISTRICT        0
GANG_RELATED              0
UNIT_ID                   0
UNIT_NAME                 0
LONGITUDE              4136
LATITUDE               4136
PART_CATEGORY             0
dtype: int64

In [65]:
#Change data types
f2019 = pd.DataFrame(f2019)
f2019[['CATEGORY', 'STAT_DESC', 'ADDRESS', 'STREET', 'CITY', 'INCIDENT_ID', 'GANG_RELATED', 'UNIT_ID', 'UNIT_NAME']] = f2019[['CATEGORY', 'STAT_DESC', 'ADDRESS', 'STREET', 'CITY', 'INCIDENT_ID', 'GANG_RELATED', 'UNIT_ID', 'UNIT_NAME']].astype('string')
#f2019['ZIP'] = f2019['ZIP'].astype('Int64')
f2019.dtypes

INCIDENT_DATE         datetime64[ns]
CATEGORY                      string
STAT                           int64
STAT_DESC                     string
ADDRESS                       string
STREET                        string
CITY                          string
ZIP                          float64
INCIDENT_ID                   string
REPORTING_DISTRICT             int64
GANG_RELATED                  string
UNIT_ID                       string
UNIT_NAME                     string
LONGITUDE                    float64
LATITUDE                     float64
PART_CATEGORY                  int64
dtype: object

In [43]:
import geopy

dfT = f2019.head(10)

def get_zipcode(df, geolocator, lat_field, lon_field):
    if ((dfT[lat_field].notna()) & (dfT[lon_field].notna())):
        location = geolocator.reverse((df[lat_field], df[lon_field]))
        return location.raw['address']['postcode']
    else:
        return 0

geolocator = geopy.Nominatim(user_agent='1234')

#zCode = f2019.apply(get_zipcode, geolocator=geolocator, axis=1, lat_field='LATITUDE', lon_field='LONGITUDE')
zmask = (dfT['ZIP'].isnull() and (dfT['LATITUDE'].notna()))
dfT.loc[zmask, 'ZIP'] = dfT.apply(get_zipcode, geolocator=geolocator, axis=1, lat_field='LATITUDE', lon_field='LONGITUDE')
dfT
#zCode

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

### Data Checks

In [8]:
#Data types
f2019.dtypes

INCIDENT_DATE         datetime64[ns]
CATEGORY                      string
STAT                           int64
STAT_DESC                     string
ADDRESS                       string
STREET                        string
CITY                          string
ZIP                            Int64
INCIDENT_ID                   string
REPORTING_DISTRICT             int64
GANG_RELATED                  string
UNIT_ID                       string
UNIT_NAME                     string
LONGITUDE                    float64
LATITUDE                     float64
PART_CATEGORY                  int64
dtype: object

In [101]:
#Length (columns)
len(f2019.columns)

16

In [102]:
#Length (rows)
len(f2019)

81194

In [11]:
#Rows and columns
f2019.shape

(81194, 16)

In [12]:
#Duplicates
f2019.duplicated()

153216    False
44889     False
153043    False
143678    False
10582     False
          ...
57089     False
58322     False
85793     False
36816     False
100263    False
Length: 81194, dtype: bool

In [13]:
#Duplicates (Count)
f2019.duplicated().sum()

0

In [14]:
#Count null values for each column
f2019.isnull().sum()

INCIDENT_DATE             0
CATEGORY                  0
STAT                      0
STAT_DESC                 0
ADDRESS                 765
STREET                 1113
CITY                    765
ZIP                   37193
INCIDENT_ID               0
REPORTING_DISTRICT        0
GANG_RELATED              0
UNIT_ID                   0
UNIT_NAME                 0
LONGITUDE              4136
LATITUDE               4136
PART_CATEGORY             0
dtype: int64

In [15]:
#Unique values
f2019.nunique()

INCIDENT_DATE         54584
CATEGORY                 30
STAT                    227
STAT_DESC               227
ADDRESS               46810
STREET                37995
CITY                    239
ZIP                     292
INCIDENT_ID           81193
REPORTING_DISTRICT     1090
GANG_RELATED              2
UNIT_ID                  52
UNIT_NAME                53
LONGITUDE              1132
LATITUDE                998
PART_CATEGORY             2
dtype: int64

In [ ]:
f2019.dtypes

### Initial Findings

In [73]:
#Count by Station Name
uname = f2019.groupby(['UNIT_NAME'])['INCIDENT_ID'].count().reset_index()
uname

                               UNIT_NAME  INCIDENT_ID
0                                  ADMIN           97
1                               ALTADENA          788
2                                 AVALON          118
3                                 CARSON         3586
4                                CENTURY         5978
5                               CERRITOS         1754
6               COMMUNITY COLLEGE BUREAU          203
7       COMMUNITY ORIENTED POLICING SVCS           22
8                                COMPTON         5158
9                    COUNTY SERVICES BUR          213
10  COURT SERVICES TRANSPORTATION BUREAU           37
11                                  CRDF          231
12                      CRESCENTA VALLEY          764
13                    CUSTODY OPERATIONS            2
14                                  EAST           48
15                      EAST LOS ANGELES         4862
16           FRAUD & CYBER CRIMES BUREAU           28
17              HUMAN TRAFFICKING BUREAU          176
18          HUMAN TRAFFICKING TASK FORCE          123
19                              INDUSTRY         4946
20                INMATE RECEPTION CENTR          681
21        INVEST. SVCS-JAIL INVEST. UNIT            2
22                INVESTIGATIVE SERVICES           42
23                              LAKEWOOD         6669
24                             LANCASTER         7032
25                                  LCMC            1
26                                LOMITA         1085
27       LOS ANGELES COUNTY SHERIFF DEPT           14
28                   MAJOR CRIMES BUREAU           75
29                     MALIBU/LOST HILLS         1990
30                        MARINA DEL REY          770
31                    MEN'S CENTRAL JAIL          699
32                      METROLINK BUREAU           91
33                      NARCOTICS BUREAU          301
34        NORTH COUNTY CORRECTIONAL FAC.          627
35                               NORWALK         4683
36                 OPER SAFE STREETS BUR           11
37                              PALMDALE         4383
38                          PARKS BUREAU           56
39                           PDC - NORTH          102
40                           PDC - SOUTH          108
41                           PICO RIVERA         2255
42                             SAN DIMAS         1736
43                  SANTA CLARITA VALLEY         4122
44                     SOUTH LOS ANGELES         3151
45             SPECIAL ENFORCEMENT (SEB)            6
46                                TEMPLE         4457
47                      TRANSIT SERV BUR          584
48                                  TRAP          157
49                                  TTCF          515
50                                WALNUT         2699
51                                  WEST           79
52                        WEST HOLLYWOOD         2877

In [74]:
#Count by City
cy = f2019.groupby(['CITY'])['INCIDENT_ID'].count().reset_index()
cy

                               CITY  INCIDENT_ID
0                           ABILENE            1
1                             ACTON          146
2                            AGOURA           50
3                      AGOURA HILLS          435
4                        AGUA DULCE           25
..                              ...          ...
234                   WINDSOR HILLS            1
235                        WINNETKA            1
236                  WOODLAND HILLS           26
237  WRIGHTWOOD-FALLING SPRINGS N F            2
238                     YORBA LINDA            1

[239 rows x 2 columns]

In [74]:
#Top 5 by Category
c = f2019.groupby(['CATEGORY'])['INCIDENT_ID'].count().sort_values(ascending=False).reset_index().head(5)
c

                  CATEGORY  INCIDENT_ID
0            LARCENY THEFT        15223
1   VEHICLE / BOATING LAWS         9842
2                NARCOTICS         8825
3  NON-AGGRAVATED ASSAULTS         6548
4                VANDALISM         4898

In [75]:
#Count of Part I Crime or Part II Crime indicator
part = f2019.groupby(['PART_CATEGORY'])['INCIDENT_ID'].count().reset_index()
part

   PART_CATEGORY  INCIDENT_ID
0              1        31332
1              2        49862

In [76]:
#Count of gang related incident 
gang = f2019.groupby(['GANG_RELATED'])['INCIDENT_ID'].count().reset_index()
gang

  GANG_RELATED  INCIDENT_ID
0           NO        80085
1          YES         1109

### Export

In [44]:
#Export to csv
f2019.to_csv('C:/Users/hanna/Documents/CSV/CRIMESDATA/LA_2019.csv')

### 2019 July - December

In [17]:
#Filter by Q3/Q4 2019
start_date = '2019-06-30 23:59:59'
end_date = '2019-12-31 23:59:59'

mask = (raw2019['INCIDENT_DATE'] > start_date) & (raw2019['INCIDENT_DATE'] <= end_date)
e2019 = raw2019.loc[mask]
e2019.reset_index(drop=True)
e2019.shape

(79146, 19)

### 2019 - Incidents that did not occur in 2019 but were reported in 2019

In [18]:
mask = (raw2019['INCIDENT_DATE'].dt.year != 2019)
nr2019 = raw2019.loc[mask]
nr2019.reset_index(drop=True)
nr2019.shape

(3098, 19)